spring:
  application:
    name: mySoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/yupao
  session:
    timeout: 86400
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    port: 6379
    host: localhost
    database: 2

  profiles:
    active: dev


server:
  port: 8080
  servlet:
    session:
      cookie:
        domain: localhost
#  session失效时间



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
